services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\ScheduleBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Search,Timeline}'

    # Controller services.
    Bkstg\ScheduleBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Doctrine event listeners.
    Bkstg\ScheduleBundle\EventListener\FullCompanyListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    Bkstg\ScheduleBundle\EventListener\InvitationAutoAcceptListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
