services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\ScheduleBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Controller services.
    Bkstg\ScheduleBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Spread services.
    Bkstg\ScheduleBundle\Spread\:
        resource: '../../Spread'
        public: true
        tags:
            - { name: spy_timeline.spread }

    # Doctrine event listeners.
    Bkstg\ScheduleBundle\EventListener\FullCompanyListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    Bkstg\ScheduleBundle\EventListener\InvitationCreator:
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
    Bkstg\ScheduleBundle\EventListener\EventCreator:
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
