services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\ScheduleBundle\Timeline\:
        resource: '../../Timeline/*'

    # Spread services.
    Bkstg\ScheduleBundle\Timeline\Spread\:
        resource: '../../Timeline/Spread'
        public: true
        tags:
            - { name: spy_timeline.spread }
