Bkstg\ScheduleBundle\Entity\Event:
    properties:
        invitations:
            - All:
                - Type:
                    type: Bkstg\ScheduleBundle\Entity\Invitation
            - Valid: ~
