# Calendar paths.
bkstg_calendar_production:
    prefix: /{production_slug}/calendar
    resource: '@BkstgScheduleBundle/Resources/config/routing/calendar_production.yml'
bkstg_calendar_personal:
    prefix: /calendar/personal
    resource: '@BkstgScheduleBundle/Resources/config/routing/calendar_personal.yml'

# Schedule paths.
bkstg_schedule:
    prefix: /{production_slug}/schedule
    resource: '@BkstgScheduleBundle/Resources/config/routing/schedule.yml'

# Event paths.
bkstg_event:
    prefix: /{production_slug}/schedule/event
    resource: '@BkstgScheduleBundle/Resources/config/routing/event.yml'

# Invitation paths.
bkstg_invitation:
    prefix: /calendar/invitations
    resource: '@BkstgScheduleBundle/Resources/config/routing/invitation.yml'
